#import "@preview/touying:0.5.5": *
#import themes.simple: *

#show: simple-theme.with(
  aspect-ratio: "16-9",
  config-info(
    title: [AFM Force-Distance Analysis of Suspended COF Film (JJS)],
    subtitle: [PeakForce QNM Mode · Snap-in Dynamics \& Mechanism],
    author: [Li Shuang \& Prof. Kejun Liu],
    date: datetime(year: 2026, month: 4, day: 23),
  ),
)

#set text(font: ("New Computer Modern", "Noto Sans SC"), size: 15pt)
#set math.equation(numbering: none)

#let primary = rgb("#1a5276")
#let accent = rgb("#e74c3c")
#let soft = rgb("#5d6d7e")

// ── CSV loaders ──────────────────────────────────────────────────
#let summary-csv = csv("../results/jjs_report_data/summary.csv")
#let summary-h = summary-csv.at(0)
#let summary-r = summary-csv.slice(1)

#let disp-csv = csv("../results/jjs_report_data/displacement.csv")
#let disp-h = disp-csv.at(0)
#let disp-r = disp-csv.slice(1)

#let theory-csv = csv("../results/jjs_report_data/theory.csv")
#let theory-h = theory-csv.at(0)
#let theory-r = theory-csv.slice(1)

#let asym-csv = csv("../results/jjs_report_data/asymmetry.csv")
#let asym-h = asym-csv.at(0)
#let asym-r = asym-csv.slice(1)

#let energy-csv = csv("../results/jjs_report_data/energy.csv")
#let energy-h = energy-csv.at(0)
#let energy-r = energy-csv.slice(1)

#let const-csv = csv("../results/jjs_report_data/constants.csv")
#let const-h = const-csv.at(0)
#let const-r = const-csv.slice(1)

// ── Helper: native bar chart (no cetz) ───────────────────────────
#let bar-chart(data, labels, colors: (blue,), width: 10, height: 4, y-max: none) = {
  let vals = data.map(x => float(x))
  let n = vals.len()
  let ymax = if y-max != none { y-max } else { calc.max(..vals) * 1.1 }
  let bar-w = width / n * 0.7
  let gap = width / n * 0.3
  box(width: width * 1cm, height: height * 1cm)[
    #for (i, v) in vals.enumerate() {
      let x0 = gap + i * (bar-w + gap)
      let h = v / ymax * height
      place(dx: x0 * 1cm, dy: (height - h) * 1cm)[
        #rect(width: bar-w * 1cm, height: h * 1cm, fill: colors.at(calc.rem(i, colors.len())))
      ]
      place(dx: (x0 + bar-w / 2) * 1cm, dy: height * 1cm + 0.1cm)[
        #align(center)[#rotate(-45deg, origin: center)[#text(size: 6pt, labels.at(i))]]
      ]
    }
    #place(dx: 0cm, dy: 0cm)[#line(length: width * 1cm, stroke: 0.5pt)]
    #place(dx: 0cm, dy: 0cm)[#line(angle: 90deg, length: height * 1cm, stroke: 0.5pt)]
  ]
}

// ── Helper: native scatter plot (no cetz) ────────────────────────
#let scatter-plot(xs, ys, x-label: "", y-label: "", width: 8, height: 4) = {
  let xvals = xs.map(x => float(x))
  let yvals = ys.map(y => float(y))
  let xmin = calc.min(..xvals) * 0.9
  let xmax = calc.max(..xvals) * 1.1
  let ymin = calc.min(..yvals) * 0.9
  let ymax = calc.max(..yvals) * 1.1
  box(width: width * 1cm, height: height * 1cm)[
    #for (x, y) in xvals.zip(yvals) {
      let px = (x - xmin) / (xmax - xmin) * width
      let py = (y - ymin) / (ymax - ymin) * height
      place(dx: px * 1cm, dy: (height - py) * 1cm)[
        #circle(radius: 0.08cm, fill: accent)
      ]
    }
    #place(dx: width * 0.5 * 1cm, dy: -0.3cm)[#align(center)[#text(size: 9pt, x-label)]]
    #place(dx: -0.3cm, dy: height * 0.5 * 1cm)[#align(center)[#text(size: 9pt, y-label)]]
    #place(dx: 0cm, dy: 0cm)[#line(length: width * 1cm, stroke: 0.5pt)]
    #place(dx: 0cm, dy: 0cm)[#line(angle: 90deg, length: height * 1cm, stroke: 0.5pt)]
  ]
}

// ═════════════════════════════════════════════════════════════════
//  SLIDE 1: Title (auto-generated by simple-theme)
// ═════════════════════════════════════════════════════════════════

= Outline

#outline(title: none)

= I. Experimental Setup <touying:hidden>

== Sample \& Probe Parameters

#grid(
  columns: (1fr, 1fr),
  gutter: 1em,
  [
    #table(
      columns: (auto, auto, auto),
      inset: 8pt,
      align: center + horizon,
      table.header([*Parameter*], [*Value*], [*Unit*]),
      ..const-r.slice(0, 5).flatten()
    )
  ],
  [
    #table(
      columns: (auto, auto, auto),
      inset: 8pt,
      align: center + horizon,
      table.header([*Parameter*], [*Value*], [*Unit*]),
      ..const-r.slice(5, 10).flatten()
    )
  ]
)
#v(0.3em)
#text(size: 12pt, fill: soft)[
  Film: 2D COF, ~10 nm thick, suspended over SiN pore (diameter 20 μm). 11 valid force curves, air ambient, RH > 60%.
]

== PeakForce QNM: A Dynamic Mode

#grid(
  columns: (1.2fr, 1fr),
  gutter: 1em,
  [
    #text(size: 12pt)[
      - Probe oscillates at ~#text(fill: accent)[2 kHz] with amplitude ~50–100 nm
      - Each cycle: approach → contact → retraction
      - #text(fill: accent)[High approach velocity]: $v ~ 0.1–1$ m/s
      - Force setpoint: 8–50 nN (too low for deep indentation)
      - 512 data points per curve
    ]
    #v(0.3em)
    #text(size: 12pt, fill: soft)[
      Key implication: snap-in is a *dynamic* event, not quasi-static equilibrium.
    ]
  ],
  [
    #rect(width: 100%, height: 5cm, fill: rgb("#f8f9fa"), radius: 4pt, inset: 8pt)[
      #align(center)[
        #text(size: 12pt, weight: "bold")[Force vs Time (one cycle)]
        #v(0.3em)
        #box(width: 7cm, height: 4cm)[
          #place(dx: 0cm, dy: 4cm)[#line(length: 7cm, stroke: 0.5pt)]
          #place(dx: 0cm, dy: 0cm)[#line(angle: 90deg, length: 4cm, stroke: 0.5pt)]
          #place(dx: 0cm, dy: 0cm)[#polygon(fill: none, stroke: primary, (0cm, 4cm), (0.8cm, 2.2cm), (1.6cm, 1cm), (2.4cm, 1.6cm), (3.2cm, 2.8cm), (4cm, 3.4cm), (4.8cm, 3.7cm), (5.6cm, 4cm))]
          #place(dx: 2.5cm, dy: 0.5cm)[#text(size: 8pt, fill: accent)[snap-in]]
          #place(dx: 3.5cm, dy: 4.3cm)[#text(size: 8pt)[Time]]
          #place(dx: -0.3cm, dy: 2cm)[#text(size: 8pt)[F]]
        ]
      ]
    ]
  ]
)

== Two-Stage Framework

#grid(
  columns: (1fr, 1fr),
  gutter: 1em,
  [
    #rect(width: 100%, fill: rgb("#eaf2f8"), radius: 4pt, inset: 8pt)[
      #text(weight: "bold", fill: primary)[Stage 1: Snap-in (F < 0)]
      #v(0.3em)
      - Surface interaction domain
      - vdW, capillary, electrostatic
      - Data: #text(fill: accent)[abundant] (11/11 curves)
      - Reliable for mechanism analysis
    ]
    #v(0.3em)
    #rect(width: 100%, fill: rgb("#fdf2e9"), radius: 4pt, inset: 8pt)[
      #text(weight: "bold", fill: accent)[Stage 2: Repulsive (F ≥ 0)]
      #v(0.3em)
      - Film mechanical response
      - Elastic deformation, bending
      - Data: #text(fill: accent)[insufficient] (1–5 points)
      - Cannot extract $sigma_0$, $k_m$
    ]
  ],
  [
    #rect(width: 100%, height: 5cm, fill: rgb("#f8f9fa"), radius: 4pt, inset: 8pt)[
      #align(center)[
        #text(size: 12pt, weight: "bold")[Schematic F-Z Curve]
        #v(0.3em)
        #box(width: 6cm, height: 4cm)[
          #place(dx: 0cm, dy: 0cm)[#line(length: 6cm, stroke: 0.5pt)]
          #place(dx: 0cm, dy: 0cm)[#line(angle: 90deg, length: 4cm, stroke: 0.5pt)]
          #place(dx: 0cm, dy: 0cm)[#polygon(fill: none, stroke: primary, (1cm, 0.5cm), (1.5cm, 3cm), (2cm, 3.8cm))]
          #place(dx: 0cm, dy: 0cm)[#polygon(fill: none, stroke: accent, (2cm, 3.8cm), (3cm, 2.5cm), (4cm, 1cm))]
          #place(dx: 1.5cm, dy: 2.2cm)[#text(size: 7pt, fill: primary)[Stage 1]]
          #place(dx: 3.2cm, dy: 1.8cm)[#text(size: 7pt, fill: accent)[Stage 2]]
          #place(dx: 1.8cm, dy: 4.1cm)[#text(size: 7pt)[Contact]]
          #place(dx: -0.3cm, dy: 2cm)[#text(size: 8pt)[F]]
          #place(dx: 5.5cm, dy: 4.1cm)[#text(size: 8pt)[Z]]
          #place(dx: 2cm, dy: 3.8cm)[#circle(radius: 0.05cm, fill: black)]
        ]
      ]
    ]
  ]
)

= II. Theoretical Background <touying:hidden>

== van der Waals Force (Non-Retarded, DMT)

#grid(
  columns: (1.2fr, 1fr),
  gutter: 1em,
  [
    #text(size: 12pt)[
      For a sphere of radius $R$ at distance $d$ from a plane, the non-retarded van der Waals force is:
    ]
    #v(0.3em)
    #align(center)[
      $ F_(v d W) = (A R) / (12 d_0^2) $
    ]
    #v(0.3em)
    #text(size: 12pt)[
      where $A$ = Hamaker constant, $d_0$ = cutoff distance (~0.3 nm).
    ]
    #v(0.3em)
    #rect(width: 100%, fill: rgb("#eaf2f8"), radius: 4pt, inset: 7pt)[
      #text(size: 12pt)[
        With $A = 4 times 10^(-19)$ J, $R = 8$ nm, $d_0 = 0.3$ nm:
        #align(center)[
          $F_(v d W) = #theory-r.at(0).at(0)$ nN
        ]
      ]
    ]
  ],
  [
    #rect(width: 100%, fill: rgb("#f8f9fa"), radius: 4pt, inset: 8pt)[
      #text(size: 12pt, weight: "bold")[Physical picture]
      #v(0.3em)
      #text(size: 11pt)[
        - Fluctuating dipoles induce correlated dipoles across the gap
        - $F prop A$: stronger for higher polarizability contrast
        - $F prop R$: larger probe → more interacting volume
        - $F prop 1/d_0^2$: diverges at contact
      ]
    ]
  ]
)

== Capillary Force (Kelvin Equation)

#grid(
  columns: (1.2fr, 1fr),
  gutter: 1em,
  [
    #text(size: 12pt)[
      For a spherical probe contacting a liquid film (complete wetting, $theta = 0$):
    ]
    #v(0.3em)
    #align(center)[
      $ F_(c a p) = 4 pi R gamma $
    ]
    #v(0.3em)
    #text(size: 12pt)[
      where $gamma$ = surface tension of water (72 mN/m at 25° C).
    ]
    #v(0.3em)
    #rect(width: 100%, fill: rgb("#eaf2f8"), radius: 4pt, inset: 7pt)[
      #text(size: 12pt)[
        With $R = 8$ nm, $gamma = 72$ mN/m:
        #align(center)[
          $F_(c a p) = #theory-r.at(0).at(1)$ nN
        ]
      ]
    ]
  ],
  [
    #rect(width: 100%, fill: rgb("#f8f9fa"), radius: 4pt, inset: 8pt)[
      #text(size: 12pt, weight: "bold")[Caveats]
      #v(0.3em)
      #text(size: 11pt)[
        - Assumes equilibrium liquid bridge
        - Dynamic approach may over/under-estimate $gamma$
        - Nanoscale contact angle $theta$ unknown
        - Adsorbed water layer thickness affects $R_(e f f)$
      ]
    ]
  ]
)

== Casimir-Polder Force (Retarded vdW)

#grid(
  columns: (1.2fr, 1fr),
  gutter: 1em,
  [
    #text(size: 12pt)[
      At large separations ($d >> lambda_0$), retardation reduces the power law from $d^(-2)$ to $d^(-3)$:
    ]
    #v(0.3em)
    #align(center)[
      $ F_(C P) = (pi^3 planck c R) / (360 d_0^3) dot eta $
    ]
    #v(0.3em)
    #text(size: 12pt)[
      where $eta approx 0.4$ for polymer/SiN interfaces.
    ]
    #v(0.3em)
    #rect(width: 100%, fill: rgb("#eaf2f8"), radius: 4pt, inset: 7pt)[
      #text(size: 12pt)[
        With $R = 8$ nm, $d_0 = 0.3$ nm:
        #align(center)[
          $F_(C P) approx 0.04$ nN
        ]
      ]
    ]
  ],
  [
    #rect(width: 100%, fill: rgb("#f8f9fa"), radius: 4pt, inset: 8pt)[
      #text(size: 12pt, weight: "bold")[Regimes]
      #v(0.3em)
      #text(size: 11pt)[
        - $d < 5$ nm: non-retarded vdW dominates
        - $5–20$ nm: transition regime
        - $d > 20$ nm: Casimir-Polder dominates
        - For JJS snap-in ($d_0 = 0.3$ nm): CP negligible
      ]
    ]
  ]
)

== Electrostatic Force (CPD Model)

#grid(
  columns: (1.2fr, 1fr),
  gutter: 1em,
  [
    #text(size: 12pt)[
      If probe and sample have a contact potential difference $V_(C P D)$:
    ]
    #v(0.3em)
    #align(center)[
      $ F_(e l e c) = (pi epsilon_0 R V_(C P D)^2) / d_0 $
    ]
    #v(0.3em)
    #text(size: 12pt)[
      To match 120 nN with $R = 8$ nm, $d_0 = 0.3$ nm:
    ]
    #v(0.3em)
    #align(center)[
      $V_(C P D) approx 16.5$ V
    ]
    #v(0.3em)
    #text(size: 13pt, fill: accent)[
      This exceeds typical surface potentials by 30–160×.
    ]
  ],
  [
    #rect(width: 100%, fill: rgb("#f8f9fa"), radius: 4pt, inset: 8pt)[
      #text(size: 12pt, weight: "bold")[Assessment]
      #v(0.3em)
      #text(size: 11pt)[
        - Electrostatic force *could* be large if $V_(C P D) > 5$ V
        - But 16.5 V is unrealistic for COF/SiN in air
        - Humidity screens surface charges (Debye layer)
        - Conclusion: electrostatic contribution is likely minor
      ]
    ]
  ]
)

== Theory vs Experiment: The Gap

#align(center)[
  #table(
    columns: (auto, auto, auto, auto),
    inset: 10pt,
    align: center + horizon,
    table.header([*Mechanism*], [*Formula*], [*Prediction (nN)*], [*Fraction of measured*]),
    [Non-retarded vdW], [$F = A R / (12 d_0^2)$], [#theory-r.at(0).at(0)], [~2.5%],
    [Capillary], [$F = 4 pi R gamma$], [#theory-r.at(0).at(1)], [~6%],
    [Casimir-Polder], [$F = pi^3 planck c R / (360 d_0^3) eta$], [~0.04], [\<0.1%],
    [Electrostatic], [$F = pi epsilon_0 R V^2 / d_0$], [~2–10 (typical)], [~2–8%],
    table.hline(),
    [*Total classic*], [], [*~10–15*], [*~10%*],
    [*Measured*], [], [*#theory-r.at(0).at(4)–#theory-r.at(0).at(5)*], [*100%*],
  )
]
#v(0.3em)
#align(center)[
  #text(size: 16pt, weight: "bold", fill: accent)[
    Measured force = #theory-r.at(0).at(7) × classic theory sum
  ]
]

= III. Results — Snap-in Analysis <touying:hidden>

== Snap-in Force Statistics (All 11 Curves)

#text(size: 11pt)[
  #table(
    columns: (auto, auto, auto, auto, auto, auto, auto),
    inset: 5pt,
    align: center + horizon,
    table.header([*File*], [*Disp (nm)*], [*Setpoint*], [*Snap (nN)*], [*Depth (nm)*], [*Drop (N/m)*], [*Rise (N/m)*]),
    ..summary-r.map(r => (
      r.at(0).replace("JJS-50nm-", ""),
      r.at(1), r.at(2), r.at(3), r.at(4), r.at(5), r.at(6)
    )).flatten()
  )
]
#v(0.3em)
#text(size: 12pt, fill: soft)[
  Mean snap-in force: #calc.round(float(theory-r.at(0).at(5)), digits: 1) nN. All curves show systematic negative force; no anomalous positive-only curves.
]

== Snap-in Force vs Piezo Displacement

#align(center)[
  #scatter-plot(
    summary-r.map(r => r.at(1)),
    summary-r.map(r => str(calc.abs(float(r.at(3))))),
    x-label: "Piezo Displacement (nm)",
    y-label: "|Snap-in Force| (nN)"
  )
]
#v(0.3em)
#align(center)[
  #table(
    columns: (auto, auto, auto, auto, auto),
    inset: 8pt,
    align: center + horizon,
    table.header([*Disp (nm)*], [*Mean (nN)*], [*Min (nN)*], [*Max (nN)*], [*n*]),
    ..disp-r.flatten()
  )
]
#v(0.3em)
#text(size: 14pt, fill: accent)[
  Smaller displacement → stronger snap-in. Consistent with dynamic enhancement at higher approach speed.
]

== Drop vs Rise Slope Asymmetry

#align(center)[
  #bar-chart(
    asym-r.map(r => str(calc.max(float(r.at(1)), float(r.at(2))) * 1.0)),
    asym-r.map(r => r.at(0).replace("JJS-50nm-", "").replace("-NanoScope", "")),
    colors: (primary, accent),
    width: 10,
    height: 4,
    y-max: 120
  )
]
#v(0.3em)
#text(size: 12pt)[
  - Drop slopes: #calc.round(calc.min(..asym-r.map(r => float(r.at(1)))), digits: 1) – #calc.round(calc.max(..asym-r.map(r => float(r.at(1)))), digits: 1) N/m
  - Rise slopes: #calc.round(calc.min(..asym-r.map(r => float(r.at(2)))), digits: 1) – #calc.round(calc.max(..asym-r.map(r => float(r.at(2)))), digits: 1) N/m
  - Asymmetry ratio: #calc.round(calc.min(..asym-r.map(r => float(r.at(3)))), digits: 2) – #calc.round(calc.max(..asym-r.map(r => float(r.at(3)))), digits: 2)
]
#v(0.3em)
#text(size: 13pt, fill: soft)[
  Drop >> rise indicates mechanical instability (jump-to-contact), not quasi-static approach.
]

== Energy Dissipated in Transition Zone

#align(center)[
  #scatter-plot(
    energy-r.map(r => r.at(1)),
    energy-r.map(r => r.at(2)),
    x-label: "Piezo Displacement (nm)",
    y-label: "Energy (nN·nm)"
  )
]
#v(0.3em)
#text(size: 12pt)[
  Dissipated energy: #calc.round(calc.min(..energy-r.map(r => float(r.at(2)))), digits: 1) – #calc.round(calc.max(..energy-r.map(r => float(r.at(2)))), digits: 1) nN·nm. Represents viscoelastic losses in water film + plastic deformation of suspended membrane.
]

= IV. Mechanism Assessment <touying:hidden>

== Why Classic Theory Falls Short

#align(center)[
  #bar-chart(
    ("2.96", "7.24", "120.7"),
    ("vdW", "Capillary", "Measured"),
    colors: (primary, rgb("#2ecc71"), accent),
    width: 8, height: 4, y-max: 140
  )
]
#v(0.3em)
#text(size: 12pt)[
  Classic vdW + capillary predict ~10 nN. Measured: 120.7 nN (mean). The gap is #text(fill: accent)[systematic] and #text(fill: accent)[reproducible] across all 11 curves.
]

== Key Finding: A 10–15× Enhancement

#align(center)[
  #text(size: 28pt, weight: "bold", fill: accent)[
    $F_(m e a s u r e d) = (9.7 – 14.8) times F_(t h e o r y)$
  ]
]
#v(0.3em)
#grid(
  columns: (1fr, 1fr, 1fr),
  gutter: 1em,
  [
    #rect(width: 100%, fill: rgb("#eaf2f8"), radius: 4pt, inset: 7pt)[
      #text(weight: "bold", fill: primary)[Hamaker A]
      #v(0.3em)
      Required: $A approx 1.6 times 10^(-17)$ J vs. typical: $4 times 10^(-19)$ J Ratio: #text(fill: accent)[~40×]
    ]
  ],
  [
    #rect(width: 100%, fill: rgb("#eaf2f8"), radius: 4pt, inset: 7pt)[
      #text(weight: "bold", fill: primary)[Capillary]
      $F_(c a p) = 7.2$ nN Needs: ~120 nN Ratio: #text(fill: accent)[~17×]
    ]
  ],
  [
    #rect(width: 100%, fill: rgb("#eaf2f8"), radius: 4pt, inset: 7pt)[
      #text(weight: "bold", fill: primary)[Electrostatic]
      Needs: $V_(C P D) approx 16.5$ V vs. typical: 0.1–0.5 V Ratio: #text(fill: accent)[~30–160×]
    ]
  ]
)
#v(0.3em)
#text(size: 12pt)[
  #text(fill: accent)[No single classic mechanism can bridge the gap.] A collective or geometric enhancement is required.
]

== Working Hypothesis: Dynamic Capillary + Film Indentation

#text(size: 12pt)[
  We propose a #text(fill: accent)[three-stage snap-in model]:
]
#v(0.3em)
#grid(
  columns: (1fr, 1fr, 1fr),
  gutter: 1em,
  [
    #rect(width: 100%, fill: rgb("#eaf2f8"), radius: 4pt, inset: 7pt)[
      #text(weight: "bold", fill: primary)[Stage A: Approach]
      #v(0.3em)
      #text(size: 11pt)[
        - Probe approaches at $v ~ 0.1–1$ m/s
        - Water layers on tip & film overlap
        - Viscoelastic resistance builds
      ]
    ]
  ],
  [
    #rect(width: 100%, fill: rgb("#fdf2e9"), radius: 4pt, inset: 7pt)[
      #text(weight: "bold", fill: accent)[Stage B: Snap-in]
      #v(0.3em)
      #text(size: 11pt)[
        - Attractive force exceeds film stiffness
        - Film indents (downward deflection)
        - Effective contact area $>>$ tip cross-section
      ]
    ]
  ],
  [
    #rect(width: 100%, fill: rgb("#e8f8f5"), radius: 4pt, inset: 7pt)[
      #text(weight: "bold", fill: rgb("#1e8449"))[Stage C: Contact]
      #v(0.3em)
      #text(size: 11pt)[
        - Film elastic recovery begins
        - Rise slope $approx k_c$ (5 N/m)
        - Capillary bridge ruptures instantly
      ]
    ]
  ]
)
#v(0.3em)
#text(size: 12pt, fill: soft)[
  The 10–15× enhancement arises from (i) dynamic overshoot during fast approach and (ii) geometric amplification by film indentation.
]

= V. Discussion <touying:hidden>

== Why Classic Theory Fails for Suspended Films

#text(size: 12pt)[
  Classic models assume a #text(fill: accent)[rigid, infinite plane]. JJS is a #text(fill: accent)[suspended, nm-thick membrane].
]
#v(0.3em)
#grid(
  columns: (1fr, 1fr),
  gutter: 1em,
  [
    #text(size: 11pt)[
      *Rigid plane assumption:*
      - Tip interacts with only a small area
      - No mechanical deformation
      - Force scales as $R$
    ]
    #v(0.3em)
    #text(size: 11pt)[
      *Suspended film reality:*
      - Attractive pressure causes *downward indentation*
      - Effective radius $R_(e f f) >> R_(t i p)$
      - Force scales as $R_(e f f)$ or even $R_(e f f)^2$
    ]
  ],
  [
    #rect(width: 100%, height: 5cm, fill: rgb("#f8f9fa"), radius: 4pt, inset: 8pt)[
      #align(center)[
        #text(size: 12pt, weight: "bold")[Indentation geometry]
        #v(0.3em)
        #box(width: 6cm, height: 3cm)[
          #place(dx: 0cm, dy: 0cm)[#line(length: 2cm, stroke: 0.5pt)]
          #place(dx: 4cm, dy: 0cm)[#line(length: 2cm, stroke: 0.5pt)]
          #place(dx: 2cm, dy: 0.5cm)[#line(length: 2cm, stroke: primary)]
          #place(dx: 2.5cm, dy: 0.5cm)[#polygon(fill: none, stroke: accent, (0.5cm, 0cm), (0cm, 1cm), (1cm, 1cm))]
          #place(dx: 2.8cm, dy: 1.5cm)[#line(length: 0.4cm, angle: 90deg, stroke: 0.5pt)]
          #place(dx: 3.4cm, dy: 1.5cm)[#line(length: 0.4cm, angle: 90deg, stroke: 0.5pt)]
          #place(dx: 3cm, dy: 2.2cm)[#text(size: 8pt)[Tip]]
          #place(dx: 3cm, dy: -0.3cm)[#text(size: 8pt)[Pore]]
        ]
      ]
    ]
  ]
)

== PeakForce QNM Dynamic Effects

#text(size: 12pt)[
  The 2 kHz oscillation means each approach is a #text(fill: accent)[dynamic event], not static equilibrium:
]
#v(0.3em)
#grid(
  columns: (1fr, 1fr),
  gutter: 1em,
  [
    #text(size: 12pt)[
      *Viscoelastic overshoot:*
      - Water film relaxation time $tau ~ eta d^3 / gamma$
      - For $d ~ 1$ nm, $tau ~ 10^(-9)$ s
      - Probe transit time $<< tau$ → water cannot equilibrate
      - Apparent force enhanced by dynamic modulus
    ]
    #v(0.3em)
    #text(size: 12pt)[
      *Inertia of film:*
      - 10 nm film has mass $~10^(-15)$ kg per $mu$m²
      - Acceleration $a ~ F / m$ is large
      - Film "sucks" tip in during snap-in
    ]
  ],
  [
    #rect(width: 100%, fill: rgb("#f8f9fa"), radius: 4pt, inset: 8pt)[
      #text(size: 12pt, weight: "bold")[Velocity dependence]
      #v(0.3em)
      #text(size: 11pt)[
        Our data show:
        - 454 nm displacement: $F approx 151$ nN
        - 1500 nm displacement: $F approx 99$ nN
        #v(0.3em)
        Smaller displacement = higher scan speed = stronger snap-in. This is #text(fill: accent)[consistent] with dynamic enhancement.
      ]
    ]
  ]
)

== Copper Mesh vs Suspended Film

#grid(
  columns: (1fr, 1fr),
  gutter: 1em,
  [
    #text(size: 16pt, weight: "bold", fill: primary)[Copper mesh (linker1)]
    #v(0.3em)
    #text(size: 12pt)[
      - Snap-in: $-0.07$ to $-5.0$ nN
      - Most curves: purely repulsive
      - Film is mechanically constrained
      - Metal screens vdW & electrostatic
    ]
    #v(0.3em)
    #text(size: 16pt, weight: "bold", fill: accent)[JJS suspended]
    #v(0.3em)
    #text(size: 12pt)[
      - Snap-in: $-99$ to $-151$ nN
      - All curves show strong attraction
      - Film free to indent
      - No metal screening
    ]
  ],
  [
    #rect(width: 100%, fill: rgb("#f8f9fa"), radius: 4pt, inset: 8pt)[
      #align(center)[
        #text(size: 12pt, weight: "bold")[Snap-in suppression factor]
        #v(0.3em)
        #text(size: 48pt, weight: "bold", fill: accent)[20–300×]
        #v(0.3em)
        #text(size: 12pt)[
          Copper mesh suppresses snap-in by 2 orders of magnitude. This confirms that #text(fill: accent)[suspension geometry] and #text(fill: accent)[metal screening] are decisive factors.
        ]
      ]
    ]
  ]
)

= VI. Conclusions & Next Steps <touying:hidden>

== Confirmed Conclusions

#enum(
  numbering: "1.",
  [#text(fill: accent)[Snap-in is reliable and reproducible]: all 11 JJS curves show systematic negative force (−99 to −151 nN).],
  [#text(fill: accent)[Classic theory cannot explain the magnitude]: vdW + capillary predict ~10 nN; measured is 10–15× larger.],
  [#text(fill: accent)[Dynamic effects matter]: smaller displacement (higher speed) → stronger snap-in, consistent with viscoelastic enhancement.],
  [#text(fill: accent)[Film suspension is key]: copper mesh suppresses snap-in by 20–300×, proving geometry and substrate screening dominate.],
  [#text(fill: accent)[Repulsive data are insufficient]: PeakForce setpoint too low (8–50 nN) to extract membrane stiffness or prestress.]
)

== Recommended Next Experiments

#grid(
  columns: (1fr, 1fr),
  gutter: 1em,
  [
    #rect(width: 100%, fill: rgb("#eaf2f8"), radius: 4pt, inset: 7pt)[
      #text(weight: "bold", fill: primary)[To validate mechanism]
      #v(0.3em)
      #enum(
        numbering: "1.",
        [Dry environment ($"RH" < 5%$): quantify capillary contribution],
        [Variable humidity (20–80%): map $F_("snap")$ vs RH],
        [Variable probe radius ($R = 2–50$ nm): distinguish $F prop R$ vs $F prop R^2$],
        [In-situ KPFM: measure $V_(C P D)$ and electrostatic contribution],
      )
    ]
  ],
  [
    #rect(width: 100%, fill: rgb("#fdf2e9"), radius: 4pt, inset: 7pt)[
      #text(weight: "bold", fill: accent)[To extract film mechanics]
      #v(0.3em)
      #enum(
        numbering: "1.",
        [Increase setpoint to $>= 100$ nN or use contact-mode F-Z],
        [Reduce scan rate to $< 1$ Hz for denser contact data],
        [Systematic pore-diameter study: validate geometric enhancement],
      )
    ]
  ]
)

== Thank You

#align(center + horizon)[
  #text(size: 36pt, weight: "bold", fill: primary)[Thank You]
  #v(0.3em)
  #text(size: 18pt)[Questions & Discussion]
  #v(2em)
  #text(size: 12pt, fill: soft)[
    Li Shuang (Experimenter) · Prof. Kejun Liu (Analyst) April 2026
  ]
]
